// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/util"
	"gorm.io/gorm"
)

const TableNameApp = "app"

// App mapped from table <app>
type App struct {
	ID         uint64    `gorm:"column:id;comment:主键" json:"id"`                                                           // 主键
	UID        string    `gorm:"column:uid;not null;comment:用户id" json:"uid"`                                              // 用户id
	AppID      string    `gorm:"column:app_id; not null;comment:AppId" json:"app_id"`                                      // AppId
	AppSecret  string    `gorm:"column:app_secret; not null;comment:AppSecret" json:"app_secret"`                          // AppSecret
	CreateTime time.Time `gorm:"column:create_time; default:current_timestamp();comment:创建时间" json:"create_time"`          // 创建时间
	UpdateTime time.Time `gorm:"column:update_time; not null;autoUpdateTime;comment:更新时间" json:"update_time"` // 更新时间
}

func (m *App) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName App's table name
func (*App) TableName() string {
	return TableNameApp
}
