// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/util"
	"gorm.io/gorm"
)

const TableNameDeveloper = "developer"

// Developer mapped from table <developer>
type Developer struct {
	ID            uint64    `gorm:"column:id;comment:主键" json:"id"`                                                           // 主键
	DeveloperID   string    `gorm:"column:developer_id; not null;comment:开发商id" json:"developer_id"`                          // 开发商id
	DeveloperName string    `gorm:"column:developer_name; not null;comment:开发商名称" json:"developer_name"`                      // 开发商名称
	ContactPerson string    `gorm:"column:contact_person; not null;comment:联系人" json:"contact_person"`                        // 联系人
	ContactInfo   string    `gorm:"column:contact_info; not null;comment:联系方式" json:"contact_info"`                           // 联系方式
	CreateTime    time.Time `gorm:"column:create_time; not null;default:current_timestamp();comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;not null;autoUpdateTime;comment:更新时间" json:"update_time"`  // 更新时间
	DeleteTime    uint64    `gorm:"column:delete_time;not null;comment:删除时间" json:"delete_time"`                              // 删除时间
}

func (m *Developer) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName Developer's table name
func (*Developer) TableName() string {
	return TableNameDeveloper
}
