// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/util"
	"gorm.io/gorm"
)

const TableNameFile = "file"

// File mapped from table <file>
type File struct {
	ID         uint64    `gorm:"column:id;comment:主键" json:"id"`                                                          // 主键
	FileID     string    `gorm:"column:file_id;not null;comment:文件id" json:"file_id"`                                     // 文件id
	FileName   string    `gorm:"column:file_name;not null;comment:文件名称" json:"file_name"`                                 // 文件名称
	FileType   string    `gorm:"column:file_type;not null;comment:文件类型" json:"file_type"`                                 // 文件类型
	FilePath   string    `gorm:"column:file_path;not null;comment:文件保存路径" json:"file_path"`                               // 文件保存路径
	FileSize   uint64    `gorm:"column:file_size;not null;comment:文件大小 单位字节" json:"file_size"`                            // 文件大小 单位字节
	FileHash   string    `gorm:"column:file_hash;not null;comment:文件哈希值 md5" json:"file_hash"`                            // 文件哈希值 md5
	CreateTime time.Time `gorm:"column:create_time;not null;default:current_timestamp();comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;autoUpdateTime;comment:更新时间" json:"update_time"` // 更新时间
	DeleteTime uint64    `gorm:"column:delete_time;not null;comment:删除时间" json:"delete_time"`                             // 删除时间
}

func (m *File) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
