// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/util"
	"gorm.io/gorm"
)

const TableNameGatewayCollectionLog = "gateway_collection_log"

// GatewayCollectionLog mapped from table <gateway_collection_log>
type GatewayCollectionLog struct {
	ID                        int64     `gorm:"column:id;type:int;primaryKey;autoIncrement;comment:唯一id，自增" json:"id"`                                                                 // 唯一id，自增
	CollectTime               time.Time `gorm:"column:collect_time;type:datetime;comment:采集时间-每日" json:"collect_time"`                                                                   // 采集时间-每日
	SvcID                     string    `gorm:"column:svc_id;type:varchar(50);not null;comment:服务ID" json:"svc_id"`                                                                      // 服务ID
	SvcName                   string    `gorm:"column:svc_name;type:varchar(50);not null;comment:服务名称" json:"svc_name"`                                                                  // 服务名称
	SvcBelongDeptID           string    `gorm:"column:svc_belong_dept_id;type:varchar(50);comment:服务所属部门ID" json:"svc_belong_dept_id"`                                                    // 服务所属部门ID
	SvcBelongDeptName         string    `gorm:"column:svc_belong_dept_name;type:varchar(100);comment:服务所属部门名称" json:"svc_belong_dept_name"`                                              // 服务所属部门名称
	InvokeSvcDeptID           string    `gorm:"column:invoke_svc_dept_id;type:varchar(50);comment:调用服务所属部门ID" json:"invoke_svc_dept_id"`                                                // 调用服务所属部门ID
	InvokeSvcDeptName         string    `gorm:"column:invoke_svc_dept_name;type:varchar(100);comment:调用服务所属部门名称" json:"invoke_svc_dept_name"`                                          // 调用服务所属部门名称
	InvokeSystemID            string    `gorm:"column:invoke_system_id;type:varchar(50);comment:调用服务所属系统ID" json:"invoke_system_id"`                                                      // 调用服务所属系统ID
	InvokeAppID               string    `gorm:"column:invoke_app_id;type:varchar(50);comment:调用服务所属应用ID" json:"invoke_app_id"`                                                           // 调用服务所属应用ID
	InvokeIPPort              string    `gorm:"column:invoke_ip_port;type:varchar(50);comment:调用服务IP及端口" json:"invoke_ip_port"`                                                          // 调用服务IP及端口
	InvokeNum                 int       `gorm:"column:invoke_num;type:int;comment:调用次数" json:"invoke_num"`                                                                              // 调用次数
	InvokeAverageCallDuration int       `gorm:"column:invoke_average_call_duration;type:int;comment:平均调用时长" json:"invoke_average_call_duration"`                                        // 平均调用时长
}

func (m *GatewayCollectionLog) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = int64(util.GetUniqueID())
	}

	return nil
}

// TableName GatewayCollectionLog's table name
func (*GatewayCollectionLog) TableName() string {
	return TableNameGatewayCollectionLog
}
