// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/util"
	"gorm.io/gorm"
	"time"
)

const TableNameServiceDailyRecord = "service_daily_record"

// ServiceDailyRecord mapped from table <service_daily_record>
type ServiceDailyRecord struct {
	FID                   int64     `gorm:"column:f_id;comment:主键，雪花算法" json:"f_id"`                                    // 主键，雪花算法
	ServiceID             string    `gorm:"column:service_id;not null;comment:接口id" json:"service_id"`                  // 接口id
	ServiceName           string    `gorm:"column:service_name;comment:接口名称" json:"service_name"`                       // 接口名称
	ServiceDepartmentID   string    `gorm:"column:service_department_id;comment:部门id" json:"service_department_id"`     // 部门id
	ServiceDepartmentName string    `gorm:"column:service_department_name;comment:部门名称" json:"service_department_name"` // 部门名称
	ServiceType           string    `gorm:"column:service_type;comment:接口类型" json:"service_type"`                       // 接口类型
	RecordDate            time.Time `gorm:"column:record_date;not null;comment:记录日期" json:"record_date"`                // 记录日期
	SuccessCount          int       `gorm:"column:success_count;default:0;comment:成功调用次数" json:"success_count"`         // 成功调用次数
	FailCount             int       `gorm:"column:fail_count;default:0;comment:失败调用次数" json:"fail_count"`               // 失败调用次数
	OnlineCount           int       `gorm:"column:online_count;default:0;comment:上线数量" json:"online_count"`             // 上线数量
	ApplyCount            int       `gorm:"column:apply_count;default:0;comment:申请数量" json:"apply_count"`               // 申请数量
}

// TableName ServiceDailyRecord's table name
func (*ServiceDailyRecord) TableName() string {
	return TableNameServiceDailyRecord
}

func (m *ServiceDailyRecord) UniqueKey() string {
	return "f_id"
}

func (m *ServiceDailyRecord) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}
	if m.FID == 0 {
		m.FID = util.GetUniqueID()
	}
	return nil
}
