// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/util"
	"gorm.io/gorm"
)

const TableNameServiceStatsInfo = "service_stats_info"

// ServiceStatsInfo mapped from table <service_stats_info>
type ServiceStatsInfo struct {
	ID         uint64    `gorm:"column:id;comment:主键" json:"id"`                                                          // 主键
	ServiceID  string    `gorm:"column:service_id;not null;comment:接口ID" json:"service_id"`                               // 接口ID
	ApplyNum   uint64    `gorm:"column:apply_num;not null;comment:申请数" json:"apply_num"`                                  // 申请数
	PreviewNum uint64    `gorm:"column:preview_num;not null;comment:预览数" json:"preview_num"`                              // 预览数
	CreateTime time.Time `gorm:"column:create_time;not null;default:current_timestamp();comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;autoUpdateTime;comment:更新时间" json:"update_time"` // 更新时间
}

func (m *ServiceStatsInfo) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName ServiceStatsInfo's table name
func (*ServiceStatsInfo) TableName() string {
	return TableNameServiceStatsInfo
}
