// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/util"
	"gorm.io/gorm"
)

const TableNameServiceCategoryRelation = "service_category_relation"

// ServiceCategoryRelation mapped from table <service_category_relation>
type ServiceCategoryRelation struct {
	ID             int64  `gorm:"column:id;comment:唯一id，雪花算法" json:"id"`                                  // 唯一id，雪花算法
	CategoryID     string `gorm:"column:category_id;not null;comment:类目id" json:"category_id"`            // 类目id
	CategoryNodeID string `gorm:"column:category_node_id;comment:类目节点id" json:"category_node_id"`         // 类目节点id
	ServiceID      string `gorm:"column:service_id;not null;comment:接口服务id" json:"service_id"`            // 接口服务id
	DeletedAt      int64  `gorm:"column:deleted_at;not null;default:0;comment:逻辑删除时间戳" json:"deleted_at"` // 逻辑删除时间戳
}

// TableName ServiceCategoryRelation's table name
func (*ServiceCategoryRelation) TableName() string {
	return TableNameServiceCategoryRelation
}

func (m *ServiceCategoryRelation) UniqueKey() string {
	return "id"
}

func (m *ServiceCategoryRelation) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}
	if m.ID == 0 {
		m.ID = util.GetUniqueID()
	}
	return nil
}
