// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/util"
	"gorm.io/gorm"
)

const TableNameServiceGateway = "service_gateway"

// ServiceGateway mapped from table <service_gateway>
type ServiceGateway struct {
	ID         uint64    `gorm:"column:id;comment:主键" json:"id"`                                                          // 主键
	GatewayURL string    `gorm:"column:gateway_url;not null;comment:接口网关地址" json:"gateway_url"`                           // 接口网关地址
	CreateTime time.Time `gorm:"column:create_time;not null;default:current_timestamp();comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;autoUpdateTime;comment:更新时间" json:"update_time"` // 更新时间
}

func (m *ServiceGateway) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName ServiceGateway's table name
func (*ServiceGateway) TableName() string {
	return TableNameServiceGateway
}
