// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/util"
	"gorm.io/gorm"
)

const TableNameServiceParam = "service_param"

// ServiceParam mapped from table <service_param>
type ServiceParam struct {
	ID           uint64    `gorm:"column:id;comment:主键" json:"id"`                                                                                                 // 主键
	ServiceID    string    `gorm:"column:service_id;not null;comment:接口ID" json:"service_id"`                                                                      // 接口ID
	ParamType    string    `gorm:"column:param_type;not null;comment:参数类型 request 请求参数 response 返回参数" json:"param_type"`                                           // 参数类型 request 请求参数 response 返回参数
	CnName       string    `gorm:"column:cn_name;not null;comment:中文名称" json:"cn_name"`                                                                            // 中文名称
	EnName       string    `gorm:"column:en_name;not null;comment:英文名称" json:"en_name"`                                                                            // 英文名称
	AliasName    string    `gorm:"column:alias_name;not null;comment:别名" json:"alias_name"`                                                                        // 别名
	Description  string    `gorm:"column:description;not null;comment:描述" json:"description"`                                                                      // 描述
	DataType     string    `gorm:"column:data_type;not null;comment:数据类型" json:"data_type"`                                                                        // 数据类型
	Required     string    `gorm:"column:required;not null;comment:是否必填 yes必填 no非必填" json:"required"`                                                              // 是否必填 yes必填 no非必填
	Operator     string    `gorm:"column:operator;not null;comment:运算逻辑 = 等于, != 不等于, > 大于, >= 大于等于, < 小于, <= 小于等于, like 模糊匹配, in 包含, not in 不包含" json:"operator"` // 运算逻辑 = 等于, != 不等于, > 大于, >= 大于等于, < 小于, <= 小于等于, like 模糊匹配, in 包含, not in 不包含
	DefaultValue string    `gorm:"column:default_value;not null;comment:默认值" json:"default_value"`                                                                 // 默认值
	Sequence     uint32    `gorm:"column:sequence;not null;comment:序号" json:"sequence"`                                                                            // 序号
	Sort         string    `gorm:"column:sort;not null;comment:排序方式 unsorted 不排序 asc 升序 desc 降序 默认 unsorted" json:"sort"`                                          // 排序方式 unsorted 不排序 asc 升序 desc 降序 默认 unsorted
	Masking      string    `gorm:"column:masking;not null;comment:脱敏规则 plaintext 不脱敏 hash 哈希 override 覆盖 replace 替换 默认 plaintext" json:"masking"`                  // 脱敏规则 plaintext 不脱敏 hash 哈希 override 覆盖 replace 替换 默认 plaintext
	CreateTime   time.Time `gorm:"column:create_time;not null;default:current_timestamp();comment:创建时间" json:"create_time"`                                        // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;autoUpdateTime;comment:更新时间" json:"update_time"`                                        // 更新时间
	DeleteTime   uint64    `gorm:"column:delete_time;not null;comment:删除时间" json:"delete_time"`                                                                    // 删除时间
}

func (m *ServiceParam) UniqueKey() string {
	return "id"
}

func (m *ServiceParam) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName ServiceParam's table name
func (*ServiceParam) TableName() string {
	return TableNameServiceParam
}
