// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/util"
	"gorm.io/gorm"
)

const TableNameServiceResponseFilter = "service_response_filter"

// ServiceResponseFilter mapped from table <service_response_filter>
type ServiceResponseFilter struct {
	ID         uint64    `gorm:"column:id;comment:主键" json:"id"`                                                                                                 // 主键
	ServiceID  string    `gorm:"column:service_id;not null;comment:接口ID" json:"service_id"`                                                                      // 接口ID
	Param      string    `gorm:"column:param;not null;comment:返回结果过滤字段" json:"param"`                                                                            // 返回结果过滤字段
	Operator   string    `gorm:"column:operator;not null;comment:运算逻辑 = 等于, != 不等于, > 大于, >= 大于等于, < 小于, <= 小于等于, like 模糊匹配, in 包含, not in 不包含" json:"operator"` // 运算逻辑 = 等于, != 不等于, > 大于, >= 大于等于, < 小于, <= 小于等于, like 模糊匹配, in 包含, not in 不包含
	Value      string    `gorm:"column:value;not null;comment:返回结果过滤值 多个用逗号分隔" json:"value"`                                                                     // 返回结果过滤值 多个用逗号分隔
	CreateTime time.Time `gorm:"column:create_time;not null;default:current_timestamp();comment:创建时间" json:"create_time"`                                        // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;autoUpdateTime;comment:更新时间" json:"update_time"`                                        // 更新时间
	DeleteTime uint64    `gorm:"column:delete_time;not null;comment:删除时间" json:"delete_time"`                                                                    // 删除时间
}

func (m *ServiceResponseFilter) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName ServiceResponseFilter's table name
func (*ServiceResponseFilter) TableName() string {
	return TableNameServiceResponseFilter
}
