// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/util"
	"gorm.io/gorm"
)

const TableNameServiceApply = "service_apply"

// ServiceApply mapped from table <service_apply>
type ServiceApply struct {
	ID          uint64     `gorm:"column:id;comment:主键" json:"id"`                                                               // 主键
	UID         string     `gorm:"column:uid;not null;comment:用户id" json:"uid"`                                                  // 用户id
	ServiceID   string     `gorm:"column:service_id;not null;comment:接口ID" json:"service_id"`                                    // 接口ID
	ApplyDays   uint32     `gorm:"column:apply_days;not null;comment:申请天数" json:"apply_days"`                                    // 申请天数
	ApplyReason string     `gorm:"column:apply_reason;not null;comment:申请理由" json:"apply_reason"`                                // 申请理由
	ApplyID     string     `gorm:"column:apply_id;not null;comment:申请id" json:"apply_id"`                                        // 申请id
	AuditType   string     `gorm:"column:audit_type;not null;comment:审核类型 af-data-application-request 接口调用审核" json:"audit_type"` // 审核类型 af-data-application-request 接口调用审核
	AuditStatus string     `gorm:"column:audit_status;not null;comment:审核状态 auditing 审核中 pass 通过 reject 驳回" json:"audit_status"` // 审核状态 auditing 审核中 pass 通过 reject 驳回
	FlowID      string     `gorm:"column:flow_id;not null;comment:审批流程实例id" json:"flow_id"`                                      // 审批流程实例id
	ProcDefKey  string     `gorm:"column:proc_def_key;not null;comment:审核流程key" json:"proc_def_key"`                             // 审核流程key
	AuthTime    *time.Time `gorm:"column:auth_time;comment:授权时间" json:"auth_time"`                                               // 授权时间
	ExpiredTime *time.Time `gorm:"column:expired_time;comment:过期时间" json:"expired_time"`                                         // 过期时间
	CreateTime  time.Time  `gorm:"column:create_time;not null;default:current_timestamp();comment:创建时间" json:"create_time"`      // 创建时间
	UpdateTime  time.Time  `gorm:"column:update_time;not null;autoUpdateTime;comment:更新时间" json:"update_time"`      // 更新时间
}

func (m *ServiceApply) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName ServiceApply's table name
func (*ServiceApply) TableName() string {
	return TableNameServiceApply
}
