SET SCHEMA data_application_service;
-- ALTER TABLE "service" ADD COLUMN IF NOT EXISTS "info_system_id" VARCHAR(36 char) DEFAULT NULL;
-- ALTER TABLE "service" ADD COLUMN IF NOT EXISTS "apps_id" VARCHAR(36 char) DEFAULT NULL  ;
-- ALTER TABLE "service" ADD COLUMN IF NOT EXISTS "sync_flag" VARCHAR(64 char) DEFAULT NULL ;
-- ALTER TABLE "service" ADD COLUMN IF NOT EXISTS "sync_msg" TEXT DEFAULT NULL ;
-- ALTER TABLE "service" ADD COLUMN IF NOT EXISTS "update_flag" VARCHAR(64 char) DEFAULT NULL ;
-- ALTER TABLE "service" ADD COLUMN IF NOT EXISTS "update_msg" TEXT DEFAULT NULL ;
-- ALTER TABLE "service" ADD COLUMN IF NOT EXISTS "paas_id" VARCHAR(255 char) DEFAULT NULL ;
-- ALTER TABLE "service" ADD COLUMN IF NOT EXISTS "pre_path" VARCHAR(255 char) DEFAULT NULL ;
