// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"devops.aishu.cn/AISHUDevOps/AnyFabric/_git/data-masking/common/util"
	"gorm.io/gorm"
)

const TableNameUser = "demo"

// User mapped from table <user>
type Demo struct {
	ID   string `gorm:"column:id;primaryKey" json:"id"` // 主键，uuid
	Name string `gorm:"column:name" json:"name"`
}

func (m *Demo) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName User's table name
func (*Demo) TableName() string {
	return TableNameUser
}
