// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kweaver-ai/idrm-go-common/audit"
	"github.com/kweaver-ai/idrm-go-common/middleware/v1"
	impl3 "github.com/kweaver-ai/idrm-go-common/rest/authorization/impl"
	impl2 "github.com/kweaver-ai/idrm-go-common/rest/configuration_center/impl"
	impl4 "github.com/kweaver-ai/idrm-go-common/rest/data_view/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/hydra/impl"
	"github.com/kweaver-ai/idrm-go-common/trace"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/adapter/driven"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/adapter/driven/gorm"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/adapter/driven/mdl-uniquery"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/adapter/driven/microservice"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/adapter/driven/reverse_proxy"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/adapter/driven/virtual_engine"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/adapter/driver"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/adapter/driver/v1/query"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/settings"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/util"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/domain"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/infrastructure/repository"
	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/infrastructure/repository/db"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp(s *settings.Settings) (*AppRunner, func(), error) {
	client := trace.NewOtelHttpClient()
	hydra := impl.NewHydraByService(client)
	drivenUserMgnt := driven.NewUserManagementService(client)
	configuration_centerDriven := impl2.NewConfigurationCenterDrivenByService(client)
	logger := audit.Discard()
	authorizationDriven := impl3.NewDriven(client)
	authServiceInternalV1Interface, err := driven.NewAuthServiceInternalV1Interface(client)
	if err != nil {
		return nil, nil, err
	}
	middleware := v1.NewMiddleware(hydra, drivenUserMgnt, configuration_centerDriven, logger, authorizationDriven, authServiceInternalV1Interface)
	data, cleanup, err := db.NewData(s)
	if err != nil {
		return nil, nil, err
	}
	appRepo := gorm.NewAppRepo(data)
	serviceRepo := gorm.NewServiceRepo(data)
	serviceApplyRepo := gorm.NewServiceApplyRepo(data)
	configurationRepo := gorm.NewConfigurationRepo(data)
	virtualEngineRepo := virtual_engine.NewVirtualEngineRepo()
	reverseProxyRepo := reverse_proxy.NewReverseProxyRepo()
	redis := repository.NewRedis(s)
	dataViewRepo := microservice.NewDataViewRepo()
	httpClient := util.NewHTTPClient(client)
	configurationCenterRepo := microservice.NewConfigurationCenterRepo(client, httpClient)
	authServiceRepo := microservice.NewAuthServiceRepo()
	data_viewDriven := impl4.NewDataViewDriven(client)
	labelService := driven.NewConfigurationCenterLabelService(client)
	applicationService := driven.NewConfigurationCenterApplicationService(client)
	dataApplicationServiceRepo := gorm.NewDataApplicationServiceRepo(data)
	drivenMDLUniQuery := mdl_uniquery.NewMDLUniQuery()
	queryDomain := domain.NewQueryDomain(appRepo, serviceRepo, serviceApplyRepo, configurationRepo, virtualEngineRepo, reverseProxyRepo, redis, dataViewRepo, configurationCenterRepo, authServiceRepo, data_viewDriven, labelService, applicationService, dataApplicationServiceRepo, drivenMDLUniQuery)
	serviceCallRecordRepo := gorm.NewServiceCallRecordRepo(data)
	serviceCallRecordDomain := domain.NewServiceCallRecordDomain(serviceCallRecordRepo, serviceRepo, configurationCenterRepo, dataApplicationServiceRepo)
	queryController := query.NewQueryController(queryDomain, serviceCallRecordDomain, configurationRepo)
	router := &driver.Router{
		Middleware:      middleware,
		QueryController: queryController,
	}
	server := driver.NewHttpServer(s, router)
	app := newApp(server)
	appRunner := &AppRunner{
		App: app,
	}
	return appRunner, func() {
		cleanup()
	}, nil
}

// wire.go:

var appRunnerSet = wire.NewSet(wire.Struct(new(AppRunner), "*"))
