// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/demos/{pid}": {
            "post": {
                "description": "创建Demo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Demo管理"
                ],
                "summary": "创建Demo",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "default": "4a5a3cc0-0169-4d62-9442-62214d8fcd8d",
                        "description": "P ID，uuid",
                        "name": "pid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maxLength": 128,
                        "minLength": 1,
                        "type": "string",
                        "example": "demo_name",
                        "description": "Demo名称，仅支持中英文、数字、下划线及中划线，前后空格自动去除",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/demo.CreateReqBodyParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/demo.CreateRespParam"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "demo.CreateReqBodyParam": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Demo名称，仅支持中英文、数字、下划线及中划线，前后空格自动去除",
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1,
                    "example": "demo_name"
                }
            }
        },
        "demo.CreateRespParam": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "description": "DemoID",
                    "type": "string",
                    "example": "4a5a3cc0-0169-4d62-9442-62214d8fcd8d"
                },
                "name": {
                    "description": "Demo名称",
                    "type": "string",
                    "maxLength": 128,
                    "example": "demo_name"
                }
            }
        },
        "rest.HttpError": {
            "type": "object",
            "properties": {
                "cause": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "detail": {},
                "solution": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0",
	Host:             "",
	BasePath:         "/api/data-masking/v1",
	Schemes:          []string{},
	Title:            "data-masking",
	Description:      "AnyFabric data masking",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
