// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"devops.aishu.cn/AISHUDevOps/AnyFabric/_git/data-masking/adapter/controller"
	"devops.aishu.cn/AISHUDevOps/AnyFabric/_git/data-masking/adapter/controller/demo/v1"
	impl2 "devops.aishu.cn/AISHUDevOps/AnyFabric/_git/data-masking/domain/demo/impl"
	"devops.aishu.cn/AISHUDevOps/AnyFabric/_git/data-masking/infrastructure/conf"
	"devops.aishu.cn/AISHUDevOps/AnyFabric/_git/data-masking/infrastructure/repository/db"
	"devops.aishu.cn/AISHUDevOps/AnyFabric/_git/data-masking/infrastructure/repository/db/gorm/demo/impl"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp(server *conf.Server, database *db.Database) (*AppRunner, func(), error) {
	data, cleanup, err := db.NewData(database)
	if err != nil {
		return nil, nil, err
	}
	repo := impl.NewRepo(data)
	useCase := impl2.NewUseCase(repo)
	service := demo.NewService(useCase)
	router := &controller.Router{
		DemoApi: service,
	}
	restServer := controller.NewHttpServer(server, router)
	app := newApp(restServer)
	appRunner := &AppRunner{
		App: app,
	}
	return appRunner, func() {
		cleanup()
	}, nil
}

// wire.go:

var appRunnerSet = wire.NewSet(wire.Struct(new(AppRunner), "*"))
