// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kweaver-ai/idrm-go-common/audit"
	v1_2 "github.com/kweaver-ai/idrm-go-common/middleware/v1"
	"github.com/kweaver-ai/idrm-go-common/rest/auth-service/v1"
	impl3 "github.com/kweaver-ai/idrm-go-common/rest/authorization/impl"
	impl2 "github.com/kweaver-ai/idrm-go-common/rest/configuration_center/impl"
	impl4 "github.com/kweaver-ai/idrm-go-common/rest/data_catalog/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/hydra/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/user_management"
	"github.com/kweaver-ai/idrm-go-common/trace"
	"github.com/kweaver-ai/idrm-go-common/workflow"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driven/callbacks"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driven/gorm"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driven/microservice"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driven/mq"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driven/mq/consumer"
	service2 "github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driven/mq/consumer/service"
	workflow2 "github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driven/workflow"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driver"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driver/v1/audit_process_bind"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driver/v1/developer"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driver/v1/file"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driver/v1/service"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driver/v1/service_apply"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driver/v1/service_call_record"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driver/v1/service_daily_record"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driver/v1/service_stats"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driver/v1/sub_service"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/adapter/driver/v1/subject_domain"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/settings"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/common/util"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/domain"
	impl5 "github.com/kweaver-ai/dsg/services/apps/data-application-service/domain/sub_service/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/infrastructure/repository"
	"github.com/kweaver-ai/dsg/services/apps/data-application-service/infrastructure/repository/db"
	"github.com/google/wire"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func InitApp(s *settings.Settings) (*AppRunner, func(), error) {
	client := trace.NewOtelHttpClient()
	hydra := impl.NewHydraByService(client)
	drivenUserMgnt := user_management.NewUserMgntByService(client)
	driven := impl2.NewConfigurationCenterDrivenByService(client)
	mqMQ, err := mq.NewMQClient()
	if err != nil {
		return nil, nil, err
	}
	syncProducer := mqMQ.SaramaSyncProducer
	logger := audit.NewKafka(syncProducer)
	authorizationDriven := impl3.NewDriven(client)
	authServiceInternalV1Interface, err := v1.NewInternalForBase(client)
	if err != nil {
		return nil, nil, err
	}
	middleware := v1_2.NewMiddleware(hydra, drivenUserMgnt, driven, logger, authorizationDriven, authServiceInternalV1Interface)
	data, cleanup, err := db.NewData(s)
	if err != nil {
		return nil, nil, err
	}
	developerRepo := gorm.NewDeveloperRepo(data)
	developerDomain := domain.NewDeveloperDomain(developerRepo)
	developerController := developer.NewDeveloperController(developerDomain)
	dataViewRepo := microservice.NewDataViewRepo()
	httpClient := util.NewHTTPClient(client)
	configurationCenterRepo := microservice.NewConfigurationCenterRepo(client, httpClient)
	userManagementRepo := microservice.NewUserManagementRepo()
	dataSubjectRepo := microservice.NewDataSubjectRepo(httpClient)
	serviceDailyRecordRepo := gorm.NewServiceDailyRecordRepo(data)
	gormDB := db.NewGormDB(data)
	serviceCategoryRelationRepo := gorm.NewServiceCategoryRelationRepo(gormDB)
	dataCatalogRepo := microservice.NewDataCatalogRepo(httpClient)
	mqConf, err := settings.WorkflowMQConf(s)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	workflowInterface, err := workflow.NewWorkflow(client, mqConf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	callbackInterface, cleanup2, err := callbacks.NewDataApplicationServiceCallback()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serviceRepo := gorm.NewServiceRepo(data, dataViewRepo, configurationCenterRepo, userManagementRepo, dataSubjectRepo, serviceDailyRecordRepo, serviceCategoryRelationRepo, dataCatalogRepo, mqMQ, workflowInterface, callbackInterface, driven)
	redis := repository.NewRedis(s)
	serviceStatsRepo := gorm.NewServiceStatsRepo(data, redis, serviceDailyRecordRepo)
	virtualEngineRepo := microservice.NewVirtualEngineRepo()
	auditProcessBindRepo := gorm.NewAuditProcessBindRepo(data)
	workflowRestRepo := microservice.NewWorkflowRestRepo()
	basicSearchRepo := microservice.NewBasicSearchRepo()
	appRepo := gorm.NewAppRepo(data)
	authServiceRepo := microservice.NewAuthServiceRepo()
	serviceApplyRepo := gorm.NewServiceApplyRepo(data, mqMQ, serviceRepo, appRepo, configurationCenterRepo, authServiceRepo, dataSubjectRepo, workflowInterface)
	data_catalogDriven := impl4.NewDrivenImpl(client)
	authServiceV1Interface := v1.NewBaseClient(client)
	subServiceRepo := gorm.NewSubServiceImpl(gormDB)
	drivenDeployMgm := microservice.NewDeployMgm()
	serviceDomain := domain.NewServiceDomain(serviceRepo, serviceStatsRepo, dataCatalogRepo, dataViewRepo, virtualEngineRepo, configurationCenterRepo, developerRepo, auditProcessBindRepo, workflowRestRepo, basicSearchRepo, serviceApplyRepo, dataSubjectRepo, authServiceRepo, workflowInterface, userManagementRepo, data_catalogDriven, drivenUserMgnt, authServiceV1Interface, subServiceRepo, authServiceInternalV1Interface, drivenDeployMgm, driven, authorizationDriven)
	serviceController := service.NewServiceController(serviceDomain)
	fileRepo := gorm.NewFileRepo(data)
	fileDomain := domain.NewFileDomain(fileRepo)
	fileController := file.NewFileController(fileDomain)
	auditProcessBindDomain := domain.NewAuditProcessBindDomain(auditProcessBindRepo, workflowRestRepo)
	auditProcessBindController := audit_process_bind.NewAuditProcessBindController(auditProcessBindDomain)
	serviceGatewayRepo := gorm.NewServiceGateway(data)
	serviceApplyDomain := domain.NewServiceApplyDomain(appRepo, serviceApplyRepo, serviceStatsRepo, serviceRepo, serviceGatewayRepo, configurationCenterRepo, auditProcessBindRepo, workflowRestRepo, authServiceRepo, dataSubjectRepo)
	serviceApplyController := service_apply.NewServiceApplyController(serviceApplyDomain)
	serviceStatsDomain := domain.NewServiceStatsDomain(serviceStatsRepo)
	serviceStatsController := service_stats.NewServiceStatsController(serviceStatsDomain)
	subjectDomain := domain.NewSubjectDomain(serviceRepo, dataSubjectRepo)
	subjectDomainController := subject_domain.NewSubjectDomainController(subjectDomain)
	serviceCallRecordRepo := gorm.NewServiceCallRecordRepo(data, configurationCenterRepo, driven, userManagementRepo)
	gatewayCollectionLogRepo := gorm.NewGatewayCollectionLogRepo(data, configurationCenterRepo, driven)
	serviceCallRecordDomain := domain.NewServiceCallRecordDomain(serviceCallRecordRepo, gatewayCollectionLogRepo, configurationCenterRepo)
	serviceCallRecordController := service_call_record.NewServiceCallRecordController(serviceCallRecordDomain)
	serviceDailyRecordDomain := domain.NewServiceDailyRecordDomain(serviceDailyRecordRepo, serviceCallRecordRepo)
	serviceDailyRecordController := service_daily_record.NewServiceDailyRecordController(serviceDailyRecordDomain)
	useCase := impl5.NewSubServiceUseCase(serviceRepo, subServiceRepo, mqMQ, authServiceInternalV1Interface)
	subServiceService := sub_service.NewSubServiceService(useCase)
	router := &driver.Router{
		Middleware:                   middleware,
		DeveloperController:          developerController,
		ServiceController:            serviceController,
		FileController:               fileController,
		AuditProcessBindController:   auditProcessBindController,
		ServiceApplyController:       serviceApplyController,
		ServiceStatsController:       serviceStatsController,
		SubjectDomainController:      subjectDomainController,
		ServiceCallRecordController:  serviceCallRecordController,
		ServiceDailyRecordController: serviceDailyRecordController,
		AuditLogger:                  logger,
		ConfigurationCenterDriven:    driven,
		SubServiceDomainApi:          subServiceService,
	}
	server := driver.NewHttpServer(s, router)
	app := newApp(server)
	workflowConsumer := workflow2.NewConsumerAndRegisterHandlers(workflowInterface, serviceRepo, serviceApplyRepo)
	handler := service2.NewHandler(serviceRepo)
	consumerConsumer := consumer.NewConsumer(mqMQ, handler)
	entityChangeTransport := callbacks.NewEntityChangeTransport(mqMQ)
	transports := callbacks.NewTransport(gormDB, entityChangeTransport)
	appRunner := &AppRunner{
		App:                      app,
		Consumer:                 workflowConsumer,
		MQConsumer:               consumerConsumer,
		Callbacks:                transports,
		ServiceDailyRecordDomain: serviceDailyRecordDomain,
	}
	return appRunner, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var appRunnerSet = wire.NewSet(wire.Struct(new(AppRunner), "*"))
