// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/util"
	"gorm.io/gorm"
)

const TableNameApp = "app"

// App mapped from table <app>
type App struct {
	ID         uint64    `gorm:"column:id;type:bigint(20) unsigned;primaryKey" json:"id"`                                  // 主键
	UID        string    `gorm:"column:uid;type:varchar(50);not null" json:"uid"`                                          // 用户id
	AppID      string    `gorm:"column:app_id;type:varchar(255);not null" json:"app_id"`                                   // AppId
	AppSecret  string    `gorm:"column:app_secret;type:varchar(255);not null" json:"app_secret"`                           // AppSecret
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:current_timestamp()" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;autoUpdateTime" json:"update_time"`              // 更新时间
}

func (m *App) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName App's table name
func (*App) TableName() string {
	return TableNameApp
}
