// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/util"
	"gorm.io/gorm"
)

const TableNameAuditProcessBind = "audit_process_bind"

// AuditProcessBind mapped from table <audit_process_bind>
type AuditProcessBind struct {
	ID         uint64    `gorm:"column:id;type:bigint(20) unsigned;primaryKey" json:"id"`                                  // 主键
	BindID     string    `gorm:"column:bind_id;type:varchar(255);not null" json:"bind_id"`                                 // 绑定id
	AuditType  string    `gorm:"column:audit_type;type:varchar(50);not null" json:"audit_type"`                            // 审核类型 af-data-application-publish 发布审核 af-data-application-change 变更审核 af-data-application-request 调用审核
	ProcDefKey string    `gorm:"column:proc_def_key;type:varchar(128);not null" json:"proc_def_key"`                       // 审核流程key
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:current_timestamp()" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;autoUpdateTime" json:"update_time"`              // 更新时间
}

func (m *AuditProcessBind) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName AuditProcessBind's table name
func (*AuditProcessBind) TableName() string {
	return TableNameAuditProcessBind
}
