// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/util"
	"gorm.io/gorm"
)

const TableNameDeveloper = "developer"

// Developer mapped from table <developer>
type Developer struct {
	ID            uint64    `gorm:"column:id;type:bigint(20) unsigned;primaryKey" json:"id"`                                  // 主键
	DeveloperID   string    `gorm:"column:developer_id;type:varchar(255);not null" json:"developer_id"`                       // 开发商id
	DeveloperName string    `gorm:"column:developer_name;type:varchar(255);not null" json:"developer_name"`                   // 开发商名称
	ContactPerson string    `gorm:"column:contact_person;type:varchar(255);not null" json:"contact_person"`                   // 联系人
	ContactInfo   string    `gorm:"column:contact_info;type:varchar(255);not null" json:"contact_info"`                       // 联系方式
	CreateTime    time.Time `gorm:"column:create_time;type:datetime;not null;default:current_timestamp()" json:"create_time"` // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;type:datetime;not null;autoUpdateTime" json:"update_time"`              // 更新时间
	DeleteTime    uint64    `gorm:"column:delete_time;type:bigint(20) unsigned;not null" json:"delete_time"`                  // 删除时间
}

func (m *Developer) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName Developer's table name
func (*Developer) TableName() string {
	return TableNameDeveloper
}
