// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/util"
	"gorm.io/gorm"
)

const TableNameFile = "file"

// File mapped from table <file>
type File struct {
	ID         uint64    `gorm:"column:id;type:bigint(20) unsigned;primaryKey" json:"id"`                                  // 主键
	FileID     string    `gorm:"column:file_id;type:varchar(255);not null" json:"file_id"`                                 // 文件id
	FileName   string    `gorm:"column:file_name;type:varchar(255);not null" json:"file_name"`                             // 文件名称
	FileType   string    `gorm:"column:file_type;type:varchar(255);not null" json:"file_type"`                             // 文件类型
	FilePath   string    `gorm:"column:file_path;type:varchar(255);not null" json:"file_path"`                             // 文件保存路径
	FileSize   uint64    `gorm:"column:file_size;type:bigint(20) unsigned;not null" json:"file_size"`                      // 文件大小 单位字节
	FileHash   string    `gorm:"column:file_hash;type:varchar(255);not null" json:"file_hash"`                             // 文件哈希值 md5
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:current_timestamp()" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;autoUpdateTime" json:"update_time"`              // 更新时间
	DeleteTime uint64    `gorm:"column:delete_time;type:bigint(20) unsigned;not null" json:"delete_time"`                  // 删除时间
}

func (m *File) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
