// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/util"
	"gorm.io/gorm"
)

const TableNameServiceApply = "service_apply"

// ServiceApply mapped from table <service_apply>
type ServiceApply struct {
	ID          uint64    `gorm:"column:id;type:bigint(20) unsigned;primaryKey" json:"id"`                                  // 主键
	UID         string    `gorm:"column:uid;type:varchar(50);not null" json:"uid"`                                          // 用户id
	ServiceID   string    `gorm:"column:service_id;type:varchar(255);not null" json:"service_id"`                           // 接口ID
	ApplyDays   uint32    `gorm:"column:apply_days;type:int(10) unsigned;not null" json:"apply_days"`                       // 申请天数
	ApplyReason string    `gorm:"column:apply_reason;type:varchar(800);not null" json:"apply_reason"`                       // 申请理由
	ApplyID     string    `gorm:"column:apply_id;type:varchar(255);not null" json:"apply_id"`                               // 申请id
	AuditType   string    `gorm:"column:audit_type;type:varchar(100);not null" json:"audit_type"`                           // 审核类型 af-data-application-request 接口调用审核
	AuditStatus string    `gorm:"column:audit_status;type:varchar(20);not null" json:"audit_status"`                        // 审核状态 auditing 审核中 pass 通过 reject 驳回
	FlowID      string    `gorm:"column:flow_id;type:varchar(50);not null" json:"flow_id"`                                  // 审批流程实例id
	ProcDefKey  string    `gorm:"column:proc_def_key;type:varchar(128);not null" json:"proc_def_key"`                       // 审核流程key
	AuthTime    time.Time `gorm:"column:auth_time;type:datetime" json:"auth_time"`                                          // 授权时间
	ExpiredTime time.Time `gorm:"column:expired_time;type:datetime" json:"expired_time"`                                    // 过期时间
	CreateTime  time.Time `gorm:"column:create_time;type:datetime;not null;default:current_timestamp()" json:"create_time"` // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;type:datetime;not null;autoUpdateTime" json:"update_time"`              // 更新时间
}

func (m *ServiceApply) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName ServiceApply's table name
func (*ServiceApply) TableName() string {
	return TableNameServiceApply
}
