// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/util"
	"gorm.io/gorm"
)

const TableNameServiceScriptModel = "service_script_model"

// ServiceScriptModel mapped from table <service_script_model>
type ServiceScriptModel struct {
	ID              uint64    `gorm:"column:id;type:bigint(20) unsigned;primaryKey" json:"id"`                                  // 主键
	ServiceID       string    `gorm:"column:service_id;type:varchar(255);not null" json:"service_id"`                           // 接口ID
	Script          string    `gorm:"column:script;type:text" json:"script"`                                                    // 查询语句
	Page            string    `gorm:"column:page;type:varchar(10);not null" json:"page"`                                        // 是否分页 yes分页 no不分页
	PageSize        uint32    `gorm:"column:page_size;type:int(10) unsigned;not null" json:"page_size"`                         // 分页大小
	RequestExample  string    `gorm:"column:request_example;type:text" json:"request_example"`                                  // 请求示例
	ResponseExample string    `gorm:"column:response_example;type:text" json:"response_example"`                                // 返回示例
	CreateTime      time.Time `gorm:"column:create_time;type:datetime;not null;default:current_timestamp()" json:"create_time"` // 创建时间
	UpdateTime      time.Time `gorm:"column:update_time;type:datetime;not null;autoUpdateTime" json:"update_time"`              // 更新时间
	DeleteTime      uint64    `gorm:"column:delete_time;type:bigint(20) unsigned;not null" json:"delete_time"`                  // 删除时间
}

func (m *ServiceScriptModel) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName ServiceScriptModel's table name
func (*ServiceScriptModel) TableName() string {
	return TableNameServiceScriptModel
}
