// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/util"
	"gorm.io/gorm"
)

const TableNameServiceResponseFilter = "service_response_filter"

// ServiceResponseFilter mapped from table <service_response_filter>
type ServiceResponseFilter struct {
	ID         uint64    `gorm:"column:id;type:bigint(20) unsigned;primaryKey" json:"id"`                                  // 主键
	ServiceID  string    `gorm:"column:service_id;type:varchar(255);not null" json:"service_id"`                           // 接口ID
	Param      string    `gorm:"column:param;type:varchar(255);not null" json:"param"`                                     // 返回结果过滤字段
	Operator   string    `gorm:"column:operator;type:varchar(10);not null" json:"operator"`                                // 运算逻辑 = 等于, != 不等于, > 大于, >= 大于等于, < 小于, <= 小于等于, like 模糊匹配, in 包含, not in 不包含
	Value      string    `gorm:"column:value;type:varchar(255);not null" json:"value"`                                     // 返回结果过滤值 多个用逗号分隔
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:current_timestamp()" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;autoUpdateTime" json:"update_time"`              // 更新时间
	DeleteTime uint64    `gorm:"column:delete_time;type:bigint(20) unsigned;not null" json:"delete_time"`                  // 删除时间
}

func (m *ServiceResponseFilter) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName ServiceResponseFilter's table name
func (*ServiceResponseFilter) TableName() string {
	return TableNameServiceResponseFilter
}
