// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/util"
	"gorm.io/gorm"
)

const TableNameService = "service"

// Service mapped from table <service>
type Service struct {
	ID                 uint64    `gorm:"column:id;type:bigint(20) unsigned;primaryKey" json:"id"`                                                // 主键
	ServiceName        string    `gorm:"column:service_name;type:varchar(255);not null" json:"service_name"`                                     // 接口名称
	ServiceID          string    `gorm:"column:service_id;type:varchar(255);not null" json:"service_id"`                                         // 接口ID
	ServiceCode        string    `gorm:"column:service_code;type:varchar(255);not null" json:"service_code"`                                     // 接口编码
	ServicePath        string    `gorm:"column:service_path;type:varchar(255);not null" json:"service_path"`                                     // 接口路径
	Status             string    `gorm:"column:status;type:varchar(20);not null;default:draft" json:"status"`                                    // 接口状态 draft 草稿 publish 已发布
	PublishStatus      string    `gorm:"column:publish_status;type:varchar(20);not null;default:unpublished;comment:发布状态" json:"publish_status"` // 发布状态 未发布unpublished 、发布审核中pub-auditing、已发布published、发布审核未通过pub-reject、变更审核中change-auditing、变更审核未通过change-reject
	AuditType          string    `gorm:"column:audit_type;type:varchar(50);not null;default:unpublished" json:"audit_type"`                      // 审核类型 unpublished 未发布 af-data-application-publish 发布审核 af-data-application-change 变更审核
	AuditStatus        string    `gorm:"column:audit_status;type:varchar(20);not null;default:unpublished" json:"audit_status"`                  // 审核状态 unpublished 未发布 auditing 审核中 pass 通过 reject 驳回
	ApplyID            string    `gorm:"column:apply_id;type:varchar(255);not null" json:"apply_id"`                                             // 审核申请id
	ProcDefKey         string    `gorm:"column:proc_def_key;type:varchar(128);not null" json:"proc_def_key"`                                     // 审核流程key
	AuditAdvice        string    `gorm:"column:audit_advice;type:text;not null" json:"audit_advice"`                                             // 审核意见，仅驳回时有用
	BackendServiceHost string    `gorm:"column:backend_service_host;type:varchar(255);not null" json:"backend_service_host"`                     // 后台服务域名/IP
	BackendServicePath string    `gorm:"column:backend_service_path;type:varchar(255);not null" json:"backend_service_path"`                     // 后台服务路径
	DepartmentID       string    `gorm:"column:department_id;type:varchar(255);not null" json:"department_id"`                                   // 所属部门id
	DepartmentName     string    `gorm:"column:department_name;type:varchar(255);not null" json:"department_name"`
	InfoSystemID       *string   `gorm:"column:info_system_id;type:char(36);comment:信息系统id" json:"info_system_id"`                 // 信息系统id
	AppsID             *string   `gorm:"column:apps_id;type:char(36);comment:应用id" json:"apps_id"`                                 // 应用id
	SyncFlag           *string   `gorm:"column:sync_flag;type:varchar(32);comment:同步标识(success、fail)" json:"sync_flag"`            // 同步标识(success、fail)
	SyncMsg            *string   `gorm:"column:sync_msg;type:text;comment:同步信息" json:"sync_msg"`                                   // 同步信息
	UpdateFlag         *string   `gorm:"column:update_flag;type:varchar(64);comment:更新标识(success、fail)" json:"update_flag"`        // 更新标识(success、fail)
	UpdateMsg          *string   `gorm:"column:update_msg;type:text;comment:更新信息" json:"update_msg"`                               // 更新信息
	PaasID             *string   `gorm:"column:paas_id;type:varchar(255);comment:授权id" json:"paas_id"`                             // 授权id
	PrePath            *string   `gorm:"column:pre_path;type:varchar(255);comment:网关路径前缀" json:"pre_path"`                         // 部门名称
	OwnerID            string    `gorm:"column:owner_id;type:varchar(50);not null" json:"owner_id"`                                // 数据owner用户id
	OwnerName          string    `gorm:"column:owner_name;type:varchar(255);not null" json:"owner_name"`                           // 数据owner用户名
	SubjectDomainID    string    `gorm:"column:subject_domain_id;type:varchar(255);not null" json:"subject_domain_id"`             // 主题域id
	SubjectDomainName  string    `gorm:"column:subject_domain_name;type:varchar(255);not null" json:"subject_domain_name"`         // 主题域名称
	CreateModel        string    `gorm:"column:create_model;type:varchar(10);not null" json:"create_model"`                        // 创建模式 wizard 向导模式 script 脚本模式
	HTTPMethod         string    `gorm:"column:http_method;type:varchar(10);not null" json:"http_method"`                          // 请求方式 post get
	ReturnType         string    `gorm:"column:return_type;type:varchar(10);not null" json:"return_type"`                          // 返回类型 json
	Protocol           string    `gorm:"column:protocol;type:varchar(10);not null" json:"protocol"`                                // 协议 http
	FileID             string    `gorm:"column:file_id;type:varchar(255);not null" json:"file_id"`                                 // 接口文档id
	Description        string    `gorm:"column:description;type:text" json:"description"`                                          // 接口说明
	DeveloperID        string    `gorm:"column:developer_id;type:varchar(255);not null" json:"developer_id"`                       // 开发商id
	DeveloperName      string    `gorm:"column:developer_name;type:varchar(255);not null" json:"developer_name"`                   // 开发商名称
	RateLimiting       uint32    `gorm:"column:rate_limiting;type:int(10) unsigned;not null" json:"rate_limiting"`                 // 调用频次 次/秒
	Timeout            uint32    `gorm:"column:timeout;type:int(10) unsigned;not null" json:"timeout"`                             // 超时时间 秒
	ServiceType        string    `gorm:"column:service_type;type:varchar(20);not null" json:"service_type"`                        // 接口类型 service_generate 接口生成 service_register 接口注册
	FlowID             string    `gorm:"column:flow_id;type:varchar(50);not null" json:"flow_id"`                                  // 审核流程实例id
	FlowName           string    `gorm:"column:flow_name;type:varchar(200);not null" json:"flow_name"`                             // 审核流程名称
	FlowNodeID         string    `gorm:"column:flow_node_id;type:varchar(50);not null" json:"flow_node_id"`                        // 当前所处审核流程结点id
	FlowNodeName       string    `gorm:"column:flow_node_name;type:varchar(200);not null" json:"flow_node_name"`                   // 当前所处审核流程结点名称
	OnlineTime         time.Time `gorm:"column:online_time;type:datetime" json:"online_time"`                                      // 发布时间
	CreateTime         time.Time `gorm:"column:create_time;type:datetime;not null;default:current_timestamp()" json:"create_time"` // 创建时间
	UpdateTime         time.Time `gorm:"column:update_time;type:datetime;not null;autoUpdateTime" json:"update_time"`              // 更新时间
	DeleteTime         uint64    `gorm:"column:delete_time;type:bigint(20) unsigned;not null" json:"delete_time"`                  // 删除时间
}

func (m *Service) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName Service's table name
func (*Service) TableName() string {
	return TableNameService
}
