// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/util"
	"gorm.io/gorm"
)

const TableNameServiceCallRecord = "service_call_record"

// ServiceCallRecord mapped from table <service_call_record>
type ServiceCallRecord struct {
	ID                  int64     `gorm:"column:id;type:bigint(20);primaryKey;comment:唯一id，雪花算法" json:"id"`                                 // 唯一id，雪花算法
	ServiceID           string    `gorm:"column:service_id;type:char(36);not null;comment:接口uuid" json:"service_id"`                         // 接口uuid
	ServiceDepartmentID string    `gorm:"column:service_department_id;type:char(36);comment:服务方部门id" json:"service_department_id"`         // 服务方部门id
	ServiceSystemID     string    `gorm:"column:service_system_id;type:char(36);comment:服务方信息系统id" json:"service_system_id"`             // 服务方信息系统id
	ServiceAppID        string    `gorm:"column:service_app_id;type:char(36);comment:服务方应用id" json:"service_app_id"`                       // 服务方应用id
	RemoteAddress       string    `gorm:"column:remote_address;type:varchar(255);comment:调用方地址" json:"remote_address"`                    // 调用方地址
	ForwardFor          string    `gorm:"column:forward_for;type:varchar(255);comment:HTTP请求参数X-Forward-For" json:"forward_for"`             // HTTP请求参数X-Forward-For
	UserIdentification  string    `gorm:"column:user_identification;type:varchar(255);comment:调用方身份标识" json:"user_identification"`         // 调用方身份标识
	CallDepartmentID    string    `gorm:"column:call_department_id;type:char(36);comment:调用方部门id" json:"call_department_id"` // 调用方部门id
	CallInfoSystemID    string    `gorm:"column:call_info_system_id;type:char(36);comment:调用方信息系统id" json:"call_info_system_id"` // 调用方信息系统id
	CallAppID           string    `gorm:"column:call_app_id;type:char(36);comment:调用方应用id" json:"call_app_id"`               // 调用方应用id
	CallStartTime       time.Time `gorm:"column:call_start_time;type:datetime;not null;comment:调用开始时间" json:"call_start_time"`                 // 调用开始时间
	CallEndTime         *time.Time `gorm:"column:call_end_time;type:datetime;comment:调用结束时间" json:"call_end_time"`                              // 调用结束时间
	CallHTTPCode        *int       `gorm:"column:call_http_code;type:int(11);comment:调用返回http状态码" json:"call_http_code"`                       // 调用返回http状态码
	CallStatus          int       `gorm:"column:call_status;type:int(11);default:0;comment:调用状态：0失败，1成功" json:"call_status"`              // 调用状态：0失败，1成功
	ErrorMessage        string    `gorm:"column:error_message;type:text;comment:报错信息" json:"error_message"`                                   // 报错信息
	CallOtherMessage    string    `gorm:"column:call_other_message;type:text;comment:其他调用信息（预留）" json:"call_other_message"`                   // 其他调用信息（预留）
	RecordTime          time.Time `gorm:"column:record_time;type:datetime;comment:日志记录时间" json:"record_time"`                                  // 日志记录时间
}

func (m *ServiceCallRecord) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = util.GetUniqueID()
	}

	return nil
}

// TableName ServiceCallRecord's table name
func (*ServiceCallRecord) TableName() string {
	return TableNameServiceCallRecord
}


