// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/util"
	"gorm.io/gorm"
)

const TableNameServiceDataSource = "service_data_source"

// ServiceDataSource mapped from table <service_data_source>
type ServiceDataSource struct {
	ID             uint64    `gorm:"column:id;type:bigint(20) unsigned;primaryKey" json:"id"`                                  // 主键
	ServiceID      string    `gorm:"column:service_id;type:varchar(255);not null" json:"service_id"`                           // 接口ID
	DataViewID     string    `gorm:"column:data_view_id;type:varchar(255);not null" json:"data_view_id"`                       // 数据视图Id
	DataViewName   string    `gorm:"column:data_view_name;type:varchar(255);not null" json:"data_view_name"`                   // 数据视图名称
	CatalogName    string    `gorm:"column:catalog_name;type:varchar(255);not null" json:"catalog_name"`                       // 虚拟化引擎 catalog
	DataSourceID   string    `gorm:"column:data_source_id;type:varchar(255);not null" json:"data_source_id"`                   // 数据源id
	DataSourceName string    `gorm:"column:data_source_name;type:varchar(255);not null" json:"data_source_name"`               // 数据源名称
	DataSchemaID   string    `gorm:"column:data_schema_id;type:varchar(255);not null" json:"data_schema_id"`                   // 库id（预留字段，暂无数据）
	DataSchemaName string    `gorm:"column:data_schema_name;type:varchar(255);not null" json:"data_schema_name"`               // 库名
	DataTableID    string    `gorm:"column:data_table_id;type:varchar(255);not null" json:"data_table_id"`                     // 表id（预留字段，暂无数据）
	DataTableName  string    `gorm:"column:data_table_name;type:varchar(255);not null" json:"data_table_name"`                 // 表名
	CreateTime     time.Time `gorm:"column:create_time;type:datetime;not null;default:current_timestamp()" json:"create_time"` // 创建时间
	UpdateTime     time.Time `gorm:"column:update_time;type:datetime;not null;autoUpdateTime" json:"update_time"`              // 更新时间
	DeleteTime     uint64    `gorm:"column:delete_time;type:bigint(20) unsigned;not null" json:"delete_time"`                  // 删除时间
}

func (m *ServiceDataSource) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName ServiceDataSource's table name
func (*ServiceDataSource) TableName() string {
	return TableNameServiceDataSource
}
