// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-application-gateway/common/util"
	"gorm.io/gorm"
)

const TableNameServiceParam = "service_param"

// ServiceParam mapped from table <service_param>
type ServiceParam struct {
	ID                  uint64 `gorm:"column:id;type:bigint(20) unsigned;primaryKey" json:"id"`              // 主键
	ServiceID           string `gorm:"column:service_id;type:varchar(255);not null" json:"service_id"`       // 接口ID
	ParamType           string `gorm:"column:param_type;type:varchar(10);not null" json:"param_type"`        // 参数类型 request 请求参数 response 返回参数
	CnName              string `gorm:"column:cn_name;type:varchar(255);not null" json:"cn_name"`             // 中文名称
	EnName              string `gorm:"column:en_name;type:varchar(255);not null" json:"en_name"`             // 英文名称
	AliasName           string `gorm:"column:alias_name;type:varchar(255);not null" json:"alias_name"`       // 别名
	Description         string `gorm:"column:description;type:varchar(255);not null" json:"description"`     // 描述
	DataType            string `gorm:"column:data_type;type:varchar(255);not null" json:"data_type"`         // 数据类型
	Required            string `gorm:"column:required;type:varchar(10);not null" json:"required"`            // 是否必填 yes必填 no非必填
	Operator            string `gorm:"column:operator;type:varchar(10);not null" json:"operator"`            // 运算逻辑 = 等于, != 不等于, > 大于, >= 大于等于, < 小于, <= 小于等于, like 模糊匹配, in 包含, not in 不包含
	DefaultValue        string `gorm:"column:default_value;type:varchar(255);not null" json:"default_value"` // 默认值
	Sequence            uint32 `gorm:"column:sequence;type:int(10) unsigned;not null" json:"sequence"`       // 序号
	Sort                string `gorm:"column:sort;type:varchar(10);not null" json:"sort"`                    // 排序方式 unsorted 不排序 asc 升序 desc 降序 默认 unsorted
	Masking             string `gorm:"column:masking;type:varchar(10);not null" json:"masking"`              // 脱敏规则 plaintext 不脱敏 hash 哈希 override 覆盖 replace 替换 默认 plaintext
	DataProtectionQuery bool `gorm:"-"` 
	CreateTime          time.Time `gorm:"column:create_time;type:datetime;not null;default:current_timestamp()" json:"create_time"` // 创建时间
	UpdateTime          time.Time `gorm:"column:update_time;type:datetime;not null;autoUpdateTime" json:"update_time"`              // 更新时间
	DeleteTime          uint64    `gorm:"column:delete_time;type:bigint(20) unsigned;not null" json:"delete_time"`                  // 删除时间
}

func (m *ServiceParam) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName ServiceParam's table name
func (*ServiceParam) TableName() string {
	return TableNameServiceParam
}
